### ISSUE TITLE
Test failure in rest component

### ISSUE THREAD

**Issue by sundazer** [petkivim/xrd4j#9]
Running 'mvn clean install' errors with test failures:
```
  com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest#testArray ComparisonFailure
  com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest#testDeepData ComparisonFailure
  com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest#testJSONLD1 ComparisonFailure
  com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest#testMultipleStrElements ComparisonFailure
  com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest#testMultipleElements ComparisonFailure
  com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest#testNestedElements1 ComparisonFailure
  com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest#testNestedElements2 ComparisonFailure
  com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest#testNestedElements3 ComparisonFailure
  com.pkrete.xrd4j.rest.converter.XMLToJSONConverterTest#testArray ComparisonFailure
  com.pkrete.xrd4j.rest.converter.XMLToJSONConverterTest#testJSONLD1 ComparisonFailure
  com.pkrete.xrd4j.rest.converter.XMLToJSONConverterTest#testNormalize3 ComparisonFailure
```
Quick glance at error outputs seems to indicate element order is reversed from expected output:
```
testArray(com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest)  Time elapsed: 0.121 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<...id>49</id><name_en>City of Espoo</name_en><name_sv>Esbo stad</name_sv><data_source_url>www.espoo.fi</data_source_url><name_fi>Espoon kaupunki</name_fi></array><array><id>91</id><name_en>City of Helsinki</name_en><name_sv>Helsingfors stad</name_sv><data_source_url>www.hel.fi</data_source_url><name_fi>Helsingin kaupunki</name_fi...> but was:<...data_source_url>www.espoo.fi</data_source_url><name_fi>Espoon kaupunki</name_fi><name_sv>Esbo stad</name_sv><id>49</id><name_en>City of Espoo</name_en></array><array><data_source_url>www.hel.fi</data_source_url><name_fi>Helsingin kaupunki</name_fi><name_sv>Helsingfors stad</name_sv><id>91</id><name_en>City of Helsinki</name_en...>
        at junit.framework.Assert.assertEquals(Assert.java:81)
        at junit.framework.Assert.assertEquals(Assert.java:87)
        at com.pkrete.xrd4j.rest.converter.JSONToXMLConverterTest.testArray(JSONToXMLConverterTest.java:112)

```

**Comment by petkivim** [comment]
That's a known issue and it's caused by the fact that the test results are compared as strings. The order of the elements varies between different platforms (OS, Java version etc.) which is why some tests may fail even if all the required elements are present, but in wrong order. The quickest solution is to run ```mvn clean install -DskipTests=true``` when all the tests are skipped. However, a better solution is to refactor the test cases and implement them in a way that the order of the elements does not count.

**Comment by petkivim** [comment]
Fixed.
